[REFACTOR] 코드 전반적인 리펙토링 + addProduct post로직 구체적으로 정리
Team-IT-DA/Frontend pull request #157
Opened 2021-09-21 05:18 UTC by wjddnjswjd12

## 📌 개요
참고 (#156 )
서버 통신 코드를 붙이기 전 전체적인 리펙토링의 필요성을 느낌
addProduct가 제일 빨리 완성되어야 다른분들이 작업 product들이 있는지없는지를 알 수 있을 것 같고
상품 추가가 되어야 다른 로직들 처리하기가 수월할 듯 하여 post로직을 react query를 써서 좀 더 구체적으로 짜두었습니다.

## 👩‍💻 작업 사항

위에 링크를 걸어 둔 이슈를 확인해주세요

## ✅ 참고 사항

위에 링크를 걸어 둔 이슈를 확인해주세요

2021-09-21 08:26 UTC, ha3158987 commented
와 리액트 쿼리를 적용까지 해보셨다니!!!!!(감격) 🤭👏
수고하셨어요 제니!!! 시간내서 제니가 짜주신 코드 열심히 보면서 공부하겠습미다~!!

2021-09-22 10:07 UTC, damilog commented on itda-front/src/util/apis/common/interceptors.js
> +  // Add a request interceptor
와우~~ 인터셉터까지 미리~~크~~👍

2021-09-22 10:15 UTC, damilog requested changes
코드 잘봤습니다!! 리액트 쿼리부분도 미리 작성하신 부분 좋네요~ 역쉬,, 제니는 적용도 빠름~~~ 
아 apis 로 네이밍 하신 폴더는 나중에 APIs로 바꾸실꺼죠?? 😲 (request change 잘못 누름ㅎㅎ)

2021-09-22 10:16 UTC, merged

2021-09-24 06:34 UTC, ha3158987 commented on itda-front/src/components/AddProduct/AddProductSubmitLayer.tsx
> +  const blockSubmitIfBlackInputExists = () => {
엇 혹시 `blackInput`이랑 `BlackInput`은 다른 역할을 하는걸까요..? 오타인가 싶다가 혹시 제니가 의도하신 걸수도 있어서👉👈

2021-09-24 06:34 UTC, ha3158987 commented on itda-front/src/components/ProductDetail/ProductTab.tsx
> +
요소가 뷰포트 최상단이랑 교차하면 sticky탭이 적용되는 로직인걸까요?? 넘좋네요ㅎㅎ

2021-09-24 06:34 UTC, ha3158987 commented on itda-front/src/util/apis/common/interceptors.js
> +  // Add a request interceptor
와 그러게요👍👏 인터셉터라는 걸 만들어볼 생각은 못 했었는데 크..